feat(#33): gh actions for check broken/missing links
ronin-rb/ronin-rb.github.io pull request #36
Opened 2023-06-03 15:14 UTC by ervinismu

2023-06-03 21:17 UTC, postmodern requested changes
Think we can remove `gem update --system` and `gem update bundler`. `bundler` should be installed by default and shouldn't need updating (yet).

2023-06-03 21:17 UTC, postmodern commented on .github/workflows/checklinks.yaml
> +          gem install jekyll bundler
Is `bundler` getting installed twice here? I'm pretty sure we can use the default version of `bundler`.

2023-06-03 21:17 UTC, postmodern commented on .github/workflows/checklinks.yaml
> +          gem update --system --no-document
This might be overkill. Whatever version of rubygems that shipped with the installed ruby is probably fine.

2023-07-15 17:05 UTC, ervinismu commented
updated @postmodern , sorry for late response

2023-07-16 06:09 UTC, merged