Create index.md
ronin-rb/ronin-rb.github.io pull request #50
Opened 2023-10-02 22:15 UTC by Smartmind12

Adding a new index for Getting started page to start anchoring process for the broken links

Related to #48

2023-10-02 22:22 UTC, postmodern requested changes
Use `# Title` for top-level titles.

2023-10-02 22:22 UTC, postmodern commented on docs/guides/index.md
> +## Guides
Should be `# Guides`.

2023-10-02 22:33 UTC, Smartmind12 commented on docs/guides/index.md
> +## Guides
Done!

2023-10-02 22:35 UTC, postmodern approved these changes

2023-10-02 22:35 UTC, merged

2023-11-02 00:58 UTC, postmodern commented
Hacktoberfest 2023 is now over! Congratulations on successfully submitting a PR to Ronin. As mentioned in the [blog post](https://ronin-rb.dev/blog/2023/09/26/ronin-is-participating-in-hacktoberfest-2023.html), you are now eligible for **free** [Ronin stickers](https://merch.ronin-rb.dev/category/stickers)! In order to claim your free stickers, please join the [Ronin Discord server](https://discord.gg/Cw5WWnycRH), and DM me the following information:

1. Which stickers do you want?
2. Your full mailing address.

The stickers will then be mailed in a regular flat-rate envelope, from the US, without tracking. Note, it may take up to one month for International mail to arrive.