Update Ronin Ruby Shell
ronin-rb/ronin-rb.github.io pull request #53
Opened 2023-10-02 22:25 UTC by Smartmind12

Related #48 

Repairing Guides link & adding net page link to "Using ronin repos"

2023-10-02 23:34 UTC, postmodern requested changes

2023-10-02 23:34 UTC, postmodern commented on docs/guides/using-the-ronin-ruby-shell/index.md
> + <div class="level-right">
Wrong level indentation.

2023-10-02 23:43 UTC, Smartmind12 commented on docs/guides/using-the-ronin-ruby-shell/index.md
> + <div class="level-right">
Yes corrected!

2023-10-02 23:55 UTC, postmodern approved these changes

2023-10-02 23:56 UTC, merged

2023-11-02 00:57 UTC, postmodern commented
Hacktoberfest 2023 is now over! Congratulations on successfully submitting a PR to Ronin. As mentioned in the [blog post](https://ronin-rb.dev/blog/2023/09/26/ronin-is-participating-in-hacktoberfest-2023.html), you are now eligible for **free** [Ronin stickers](https://merch.ronin-rb.dev/category/stickers)! In order to claim your free stickers, please join the [Ronin Discord server](https://discord.gg/Cw5WWnycRH), and DM me the following information:

1. Which stickers do you want?
2. Your full mailing address.

The stickers will then be mailed in a regular flat-rate envelope, from the US, without tracking. Note, it may take up to one month for International mail to arrive.