feat: Custom print layout CSS rules
ronin-rb/ronin-rb.github.io pull request #59
Opened 2023-10-09 14:12 UTC by s-vamshi

Closes #18 
Custom styles for print added.

Landing Page: [Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12847102/Ronin.pdf)

Install Page: [Install _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12847123/Install._.Ronin.pdf)

FAQ Page: [Frequently Asked Questions _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12847100/Frequently.Asked.Questions._.Ronin.pdf)

Docs Page: [Documentation _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12847106/Documentation._.Ronin.pdf)

Blog Page: [Project Blog _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12847104/Project.Blog._.Ronin.pdf)

2023-10-09 14:13 UTC, s-vamshi commented
@postmodern please review print PDFs and let me know if there are any changes to be made.

2023-10-09 22:33 UTC, postmodern requested changes
Minor code linting changes needed.

2023-10-09 22:33 UTC, postmodern commented on stylesheets/print.css
> +    /* display: none; */
Remove commented out code.

2023-10-09 22:33 UTC, postmodern commented on stylesheets/print.css
> +#social-media-links svg{
Add space before `{` for consistency.

2023-10-09 22:34 UTC, postmodern commented
@s-vamshi Looks good, noticed a few CSS code linting issues. Also, could you upload a Print Preview of a Blog Post page?

2023-10-10 01:21 UTC, s-vamshi commented on stylesheets/print.css
> +    /* display: none; */
Done

2023-10-10 01:21 UTC, s-vamshi commented on stylesheets/print.css
> +#social-media-links svg{
Done and committed the changes

2023-10-10 01:27 UTC, postmodern commented
Appears that the `post-links` on each blog post, which contains the SVG icons for Redd/HackerNews/Lobsters/etc, are rendered too big. `article.post .post-links` can be hidden entirely.
[Ronin is participating in Hacktoberfest 2023! _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12851803/Ronin.is.participating.in.Hacktoberfest.2023._.Ronin.pdf)

2023-10-10 01:30 UTC, postmodern requested changes
Hide `article.post .post-links` to hide the SVG icons for Reddit/HackerNews/Lobsters/etc.

2023-10-10 01:36 UTC, s-vamshi commented
@postmodern can you check now?

2023-10-10 01:52 UTC, postmodern commented
Looks good!
[Ronin is participating in Hacktoberfest 2023! _ Ronin.pdf](https://github.com/ronin-rb/ronin-rb.github.io/files/12851913/Ronin.is.participating.in.Hacktoberfest.2023._.Ronin.pdf)

2023-10-10 01:52 UTC, postmodern approved these changes

2023-10-10 01:53 UTC, merged

2023-11-02 00:55 UTC, postmodern commented
Hacktoberfest 2023 is now over! Congratulations on successfully submitting a PR to Ronin. As mentioned in the [blog post](https://ronin-rb.dev/blog/2023/09/26/ronin-is-participating-in-hacktoberfest-2023.html), you are now eligible for **free** [Ronin stickers](https://merch.ronin-rb.dev/category/stickers)! In order to claim your free stickers, please join the [Ronin Discord server](https://discord.gg/Cw5WWnycRH), and DM me the following information:

1. Which stickers do you want?
2. Your full mailing address.

The stickers will then be mailed in a regular flat-rate envelope, from the US, without tracking. Note, it may take up to one month for International mail to arrive.